export let categoryArray = {
    address: [
        'zipCode',
        'city',
        'cityPrefix',
        'citySuffix',
        'streetName',
        'streetAddress',
        'streetSuffix',
        'streetPrefix',
        'secondaryAddress',
        'county',
        'country',
        'countryCode',
        'state',
        'stateAbbr',
        'latitude',
        'longitude',
    ],

    commerce: ['color', 'department', 'productName', 'price', 'productAdjective', 'productMaterial', 'product'],

    company: [
        'suffixes',
        'companyName',
        'companySuffix',
        'catchPhrase',
        'bs',
        'catchPhraseAdjective',
        'catchPhraseDescriptor',
        'catchPhraseNoun',
        'bsAdjective',
        'bsBuzz',
        'bsNoun',
    ],

    database: ['column', 'type', 'collation', 'engine'],

    date: ['past', 'future', 'recent', 'month', 'weekday'],

    finance: [
        'account',
        'accountName',
        'mask',
        'amount',
        'transactionType',
        'currencyCode',
        'currencyName',
        'currencySymbol',
        'bitcoinAddress',
        'iban',
        'bic',
    ],

    hacker: ['abbreviation', 'adjective', 'noun', 'verb', 'ingverb', 'phrase'],

    helpers: ['randomize', 'replaceSymbols'],

    image: [
        'image',
        'avatar',
        'imageUrl',
        'abstract',
        'animals',
        'business',
        'cats',
        'city',
        'food',
        'nightlife',
        'fashion',
        'people',
        'nature',
        'sports',
        'technics',
        'transport',
        'dataUri',
    ],

    internet: [
        'avatar',
        'email',
        'exampleEmail',
        'userName',
        'protocol',
        'url',
        'domainName',
        'domainSuffix',
        'domainWord',
        'ip',
        'ipv6',
        'userAgent',
        'color',
        'mac',
        'password',
    ],

    lorem: ['word', 'words', 'sentence', 'slug', 'sentences', 'paragraph', 'paragraphs', 'text', 'lines'],

    name: ['firstName', 'lastName', 'findName', 'jobTitle', 'prefix', 'suffix', 'title', 'jobDescriptor', 'jobArea', 'jobType'],

    phone: ['phoneNumber', 'phoneNumberFormat', 'phoneFormats'],

    random: ['number', 'arrayElement', 'objectElement', 'uuid', 'boolean', 'word', 'words', 'image', 'locale', 'alphaNumeric'],

    system: [
        'fileName',
        'commonFileName',
        'mimeType',
        'commonFileType',
        'commonFileExt',
        'fileType',
        'fileExt',
        'directoryPath',
        'filePath',
        'semver',
    ],
};

export let localesArray = [
    'az',
    'ar',
    'cz',
    'de',
    'de_AT',
    'de_CH',
    'en',
    'en_AU',
    'en_AU_ocker',
    'en_BORK',
    'en_CA',
    'en_GB',
    'en_IE',
    'en_IND',
    'en_US',
    'en_ZA',
    'es',
    'es_MX',
    'fa',
    'fi',
    'fr',
    'fr_CA',
    'fr_CH',
    'ge',
    'id_ID',
    'it',
    'ja',
    'ko',
    'nb_NO',
    'nep',
    'nl',
    'nl_BE',
    'pl',
    'pt_BR',
    'pt_PT',
    'ro',
    'ru',
    'sk',
    'sv',
    'tr',
    'uk',
    'vi',
    'zh_CN',
    'zh_TW',
];

export const createOneToOnemapping = () => {
    let newCategoryArray = [];
    Object.keys(categoryArray).map((key) =>
        categoryArray[key].map((value) => (newCategoryArray = [...newCategoryArray, { category: key, value: value, pinned: false }]))
    );
    return newCategoryArray;
};
